config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not permitted" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :birthday, :phone, :email, :likes_icecream, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<div class="mb-4">
  <%= form_with(model: friend) do |form| %>
    <% if friend.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

        <ul>
          <% friend.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-2">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control", placeholder:"Bob" %>
    </div>

    <div class="form-group mb-2">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control", placeholder:"Ross" %>
    </div>

    <div class="form-group mb-2">
      <%= form.label :birthday, class:"d-block" %>
      <%= form.date_select :birthday, {:start_year => 1900, :end_year => Time.now.year}, {:class => "form-select me-2 d-inline-block w-auto"}%>
    </div>

    <div class="form-group mb-2">
      <%= form.label :phone %>
      <%= form.text_field :phone, class:"form-control", placeholder:"+1 123 456 7890" %>
    </div>

    <div class="form-group mb-2">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control", placeholder:"email@example.com" %>
    </div>

    <div class="form-group mb-2">
      <%= form.label :likes_icecream %>
      <%= form.check_box :likes_icecream, class:"form-check-input" %>
    </div>

    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>

    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend, class:"btn btn-primary" %>
<%= link_to 'Back', friends_path, class:"btn btn-primary" %>

app/views/friends/index.html.erb
<h1 class="mb-4">Friends</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Birthday</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Likes icecream</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
        <tr class="h-auto">
          <td><%= friend.first_name %> <%= friend.last_name %></td>
          <td><%= friend.birthday %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.email %></td>
          <td><% if friend.likes_icecream %>✔️ <% end %></td>
          <td><%= link_to '📜', friend, class:"btn btn-primary btn-sm" %></td>
          <td><%= link_to '📝', edit_friend_path(friend), class:"btn btn-primary btn-sm" %></td>
          <td><%= link_to '🗑️', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-primary" %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class:"btn btn-primary" %>

app/views/friends/show.html.erb
<div class="card">
  <div class="card-body">
    <h1>
      <%= @friend.first_name %>
      <%= @friend.last_name %>
      <% if @friend.likes_icecream %>
        <span class="badge bg-secondary">🍨</span>
      <% end %>
    </h1>

    <p class="lead">
      <%= @friend.email %>
      <%= @friend.phone %>
    </p>

    <p>
      <strong>Birthday:</strong>
      <%= @friend.birthday %>
    </p>

    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-primary" %>
    <%= link_to 'Back', friends_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/home/_header.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "Friends", root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav d-flex m-0 w-100">
          <li class="nav-item">
            <%= link_to "List", friends_path, class:"nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "New", new_friend_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
          <% end %>
          <li class="nav-item me-auto">
            <%= link_to "About", home_about_path, class:"nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item btn btn-primary p-0">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_alert.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "Friends", root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav d-flex m-0 w-100">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "New", new_friend_path, class:"nav-link" %>
            </li>
            <li class="nav-item me-auto">
              <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item me-auto"></li>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item btn btn-primary p-0">
              <%= link_to "Sign up", new_user_registration_path, class:"nav-link text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <% if notice %>
      <%= render 'layouts/alert'%>
    <% end %>
    <main class="container p-0">
      <%= yield %>
    </main>
  </body>
</html>